### ISSUE TITLE
ModuleNotFoundError: No module named 'whisper_timestamped'

### ISSUE THREAD

**Issue by Milincho** [tomchang25/whisper-auto-transcribe#22]
Getting this error with 3.0 Alpha: ModuleNotFoundError: No module named 'whisper_timestamped'

![image](https://user-images.githubusercontent.com/60118859/232236396-415c27fa-e136-4f5d-bb82-c1aa90b66afd.png)

**Comment by tomchang25** [comment]
Hi @Milincho, that's weird. Are you using `webui.bat` to open the Gradio server? 
Also, if you are updating from version 2.x, make sure to delete the `venv` directory in your whisper-auto-transcribe directory first

**Comment by Milincho** [comment]
Installed whisper-timestamped and now it says this:

![image](https://user-images.githubusercontent.com/60118859/232241038-345c2ff1-e924-4f2f-97d4-db90b08fcefc.png)

**Comment by tomchang25** [comment]
Sorry, you don't need to 'install' anything except execute 'webui.bat'.
It will run a virtual environment and install all dependencies you need.

**Comment by Milincho** [comment]
Ok, did that:
![image](https://user-images.githubusercontent.com/60118859/232242374-18dfc751-ab95-4a90-ba86-5ab65d48140c.png)

But even the web UI doesn't work. It doesn't import mkv files, and when I try to add a mp4 file it says "Error" on 'Initiate job"
![image](https://user-images.githubusercontent.com/60118859/232242531-69e476bc-9cc4-428a-aade-b64e7cc191ad.png)

**Comment by Milincho** [comment]
When I uninstall whisper_timestamped it goes back to the same: ModuleNotFoundError: No module named 'whisper_timestamped'

![image](https://user-images.githubusercontent.com/60118859/232243228-843fe4f8-a971-4328-a4e8-2f4a6a249516.png)

Even with WebUI loaded:
![image](https://user-images.githubusercontent.com/60118859/232243530-97a8a10d-11d9-4c11-b58c-92c019951728.png)

**Comment by tomchang25** [comment]
@Milincho, You need to enable the python virtual environment in command mode. Additionally, could you provide more information such as the error code in webgui.bat, the filename, subtitle name, and other settings related to the GUI error?

**Comment by Milincho** [comment]
It's the 'Vocal Extractor' option that gives the error:

![image](https://user-images.githubusercontent.com/60118859/232250227-e9020a06-e00e-463b-bd79-8b127c9717f3.png)

Without this option, the GUI version works ok:
![image](https://user-images.githubusercontent.com/60118859/232250251-0351e534-622a-4664-bf38-ae7b739c8985.png)

BUT I am interested in making the CLI version work. I always use the CLI and not the GUI version.

**Comment by tomchang25** [comment]
@Milincho Thanks for your information. I will take a look at it.

**Comment by tomchang25** [comment]
fix by v3.1, this is how update to the latest version:

1. Move directory to any other location except "Program Files" and "Program Files (x86)
2. Delete venv
3. Open webui.bat until installed over
4. Open `enable_venv.bat`
5. Enjoy

**Comment by amerodeh** [comment]
Didn't work for me sadly, even deleted the repo and recloned but getting
```
(venv) C:\Users\san-a\Downloads\tools\whisper-auto-transcribe>python .\cli.py "F:\j\abc-123\abc-123.HD.mp4" --output "F:\j\abc-123\xxx.srt" -lang ja --task translate --model large --device cuda
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\tmp\tmpviibozmx\htdemucs
Separating track C:\Users\san-a\AppData\Local\Temp\tmpviibozmx
Could not load file C:\Users\san-a\AppData\Local\Temp\tmpviibozmx. Maybe it is not a supported file format?
When trying to load using ffmpeg, got the following error: FFmpeg is not installed.
When trying to load using torchaudio, got the following error: Error opening 'C:\\Users\\san-a\\AppData\\Local\\Temp\\tmpviibozmx': File contains data in an unknown format.
Traceback (most recent call last):
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\src\utils\task.py", line 83, in transcribe
    subprocess.run(cmd, check=True)
  File "C:\Users\san-a\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmpviibozmx" -o "./tmp/tmpviibozmx/" --filename "{stem}.{ext}"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\cli.py", line 106, in <module>
    cli()
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\cli.py", line 90, in cli
    subtitle_path = transcribe(
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\src\utils\task.py", line 85, in transcribe
    raise Exception(
Exception: Error. Vocal extracter unavailable. Received: demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmpviibozmx" -o "./tmp/tmpviibozmx/" --filename "{stem}.{ext}"
Error Code: Command 'demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmpviibozmx" -o "./tmp/tmpviibozmx/" --filename "{stem}.{ext}"' returned non-zero exit status 1.
```
that is despite me running the `webui.bat` and `enable_venv.bat`.

**Comment by amerodeh** [comment]
Ok this is weird, I got the error above, then within the same cmd "session", i ran the `webui.bat` and then reran the command, this time CUDA is running out of memory. Didn't happen with previous version.
```
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\tmp\tmp15_8s0zt\htdemucs
Separating track C:\Users\san-a\AppData\Local\Temp\tmp15_8s0zt
Traceback (most recent call last):
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\venv\Scripts\demucs-script.py", line 33, in <module>
    sys.exit(load_entry_point('demucs==4.0.0', 'console_scripts', 'demucs')())
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\venv\lib\site-packages\demucs\separate.py", line 163, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\venv\lib\site-packages\demucs\apply.py", line 171, in apply_model
    out = apply_model(sub_model, mix, **kwargs)
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\venv\lib\site-packages\demucs\apply.py", line 196, in apply_model
    shifted_out = apply_model(model, shifted, **kwargs)
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\venv\lib\site-packages\demucs\apply.py", line 211, in apply_model
    weight = th.cat([th.arange(1, segment // 2 + 1, device=device),
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\src\utils\task.py", line 83, in transcribe
    subprocess.run(cmd, check=True)
  File "C:\Users\san-a\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmp15_8s0zt" -o "./tmp/tmp15_8s0zt/" --filename "{stem}.{ext}"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\cli.py", line 106, in <module>
    cli()
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\cli.py", line 90, in cli
    subtitle_path = transcribe(
  File "C:\Users\san-a\Downloads\tools\whisper-auto-transcribe\src\utils\task.py", line 85, in transcribe
    raise Exception(
Exception: Error. Vocal extracter unavailable. Received: demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmp15_8s0zt" -o "./tmp/tmp15_8s0zt/" --filename "{stem}.{ext}"
Error Code: Command 'demucs --two-stems=vocals "C:\Users\san-a\AppData\Local\Temp\tmp15_8s0zt" -o "./tmp/tmp15_8s0zt/" --filename "{stem}.{ext}"' returned non-zero exit status 1.
```
 I have 48GB of ram and a 4090 so not sure what's going on, but in HWInfo I can see that it did spike in terms of load
![image](https://user-images.githubusercontent.com/11621174/232319683-4726a8b9-b25b-42f1-ad55-3395dd5b01a8.png)

**Comment by tomchang25** [comment]
> Does this mean everytime we open the command line and run the venv script, we also then have to run webui to reinstall all the dependencies?

@amerodeh 

No, the web UI is only executed once if you use the command line. This error was caused because I forgot to add the FFmpeg path to the command line. 

In addition, kindly create a new issue instead of reporting it in a closed issue.

**Comment by Milincho** [comment]
It worked now in my first test:

![image](https://user-images.githubusercontent.com/60118859/232324216-e6e32fa5-188b-4f9b-9a97-987493acd35d.png)
