### ISSUE TITLE
Subtitels repeating 

### ISSUE THREAD

**Issue by metzo007** [tomchang25/whisper-auto-transcribe#3]
A lot of srt I created from japanese have a lot of respating lines. Both with transscribe and translate.

4
0:02:10.580 --> 0:02:13.580
and very easy

5
0:02:13.580 --> 0:02:16.580
and very easy

6
0:02:16.580 --> 0:02:19.580
and very easy

7
0:02:19.580 --> 0:02:22.580
and very easy

8
0:02:22.580 --> 0:02:25.580
and very easy

9
0:02:25.580 --> 0:02:28.580
and very easy

**Comment by Milincho** [comment]
Happens to me too, both with CPU and CUDA. Looks like a bug.
You can fix it using SubtitleEdit ( https://www.nikse.dk/subtitleedit )

![image](https://user-images.githubusercontent.com/60118859/205459391-d430699f-5c41-4111-9982-b40d4237f148.png)

**Comment by tomchang25** [comment]
Will be fixed in v0.3.0.

**Comment by tomchang25** [comment]
@metzo007 It should be fixed by v3.0 If vad and ve are open
