### ISSUE TITLE
Very High RAM usage

### ISSUE THREAD

**Issue by Milincho** [tomchang25/whisper-auto-transcribe#39]
It used up 32GB of RAM up until the computer totally froze:

![image](https://user-images.githubusercontent.com/60118859/232622102-3c5be130-73f2-4df0-8496-19a1ed638445.png)

**Comment by tomchang25** [comment]
What is the size of the file you are using, and do you enable a Vocal Extractor?

**Comment by Milincho** [comment]
It's 3.69GB.
I don't know how to enable/disable Vocal Extractor, so it depends if it is enabled by default or not. This is the CLI command I use for all my files:

python cli.py "File.ext" --output "File.English.srt" -lang ja --task translate --model large

It eats all the 32GB of RAM until Windows freezes, and then it goes all the way down. 
I also use a RTX 4080 with 16GB VRAM, but the problem is with RAM.

**Comment by Milincho** [comment]
With new 0.3.2b1 version:

At these point:
![image](https://user-images.githubusercontent.com/60118859/232688510-02a3302b-b0e9-422e-b577-25add6145e3b.png)

It used 28GB of RAM:
![image](https://user-images.githubusercontent.com/60118859/232688608-6e791262-ffda-448d-a930-b5a6852c4595.png)

At the end of the process:
![image](https://user-images.githubusercontent.com/60118859/232688666-ffd78473-9a9d-4593-ac1d-fe8207bba5e8.png)

It is using 44GB of RAM:
![image](https://user-images.githubusercontent.com/60118859/232688758-c934e68f-38c1-4442-be52-0d051c46bb32.png)

This is totally absurd. No other program ever uses that much RAM for anything.

**Comment by Milincho** [comment]
And it failed anyway:
![image](https://user-images.githubusercontent.com/60118859/232689559-5dbf9a20-a09d-45ca-b5d0-369911bab0f4.png)

And it didn't clean up the temp files:

![image](https://user-images.githubusercontent.com/60118859/232689848-9dd34a48-7c00-442a-8029-c19740626d6f.png)

**Comment by tomchang25** [comment]
> And it didn't clean up the temp files:

The temporary file will be stored in the Windows temp directory and will be automatically deleted based on your Windows settings.
> It was using 44GB of RAM, This is totally absurd. No other program ever uses that much RAM for anything.

The extremely high RAM usage in big files is caused by VE(Demucs), and there is nothing I can do about it.
You can check the detailed instructions how to disable VE by running `python .\cli.py -h.`

**Comment by Milincho** [comment]
> > And it didn't clean up the temp files:
> 
> The temporary file will be stored in the Windows temp directory and will be automatically deleted based on your Windows settings.

This is not a Windows issue. Windows does not automatically delete the files in the Temp folder. It is not the Recycle Bin. It is up to each program to delete its own files.
Again, having a queue of 100 jobs will fill up the disk with many HUNDREDS of GB in temp files that Windows don't know anything about.
It is up to Whisper-auto-transcribe to delete those temp files immediately after each job is completed OR it fails.

 
> > It was using 44GB of RAM, This is totally absurd. No other program ever uses that much RAM for anything.
> 
> The extremely high RAM usage in big files is caused by VE(Demucs), and there is nothing I can do about it. You can check the detailed instructions how to disable VE by running `python .\cli.py -h.`

Then there is something wrong with that part and should be reported to them.
