### ISSUE TITLE
What'are the differences between transcribe models?

### ISSUE THREAD

**Issue by mxgc** [tomchang25/whisper-auto-transcribe#42]
In `cli.py`, three model types are listed `whisper, whisper_timestams, stable_whisper`. Could you elaborate the difference between them? @tomchang25 

Thanks for making this tool available. I used it to transcribe my entire audiobook library and it worked great!

**Comment by tomchang25** [comment]
Whisper: The original version of OpenAI's language model.

Whisper with timestamps: A GitHub project that adds VAD (Voice Activity Detection) and other improvements. In my opinion, this is the most stable version.

Stable Whisper: Another open-source project like Whisper with timestamps, but it has its own format. It is powerful, but not as stable in my opinion. It may default back to Whisper timestamps in the next version

**Comment by mxgc** [comment]
Great! Thanks for the clarification.
