### ISSUE TITLE
Can't get webui.bat running successfully

### ISSUE THREAD

**Issue by twpotato606** [tomchang25/whisper-auto-transcribe#43]
venv "D:\whisper-auto-transcribe\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 06bd1ea2b3dd98d1474eb6480381501e50b3b662
Check torch and torchvision
Fetching updates for Custom Gradio...
Checking out commint for Custom Gradio with hash: 8ac54ca7902a04ede2cb93a11ff42c6cb011b296...
Traceback (most recent call last):
  File "D:\whisper-auto-transcribe\launch.py", line 198, in <module>
    git_clone(
  File "D:\whisper-auto-transcribe\launch.py", line 169, in git_clone
    run(
  File "D:\whisper-auto-transcribe\launch.py", line 63, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 8ac54ca7902a04ede2cb93a11ff42c6cb011b296 for Custom Gradio.
Command: git -C repositories\gradio checkout 8ac54ca7902a04ede2cb93a11ff42c6cb011b296
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: 8ac54ca7902a04ede2cb93a11ff42c6cb011b296

**Comment by DavidDah** [comment]
Same error here just different lines of code

webui.bat
venv "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe-v3\venv\Scripts\Python.exe"
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Commit hash: 825b485a7599ce7b4861144adebf22887eea444c
Check torch and torchvision
Fetching updates for Custom Gradio...
Checking out commint for Custom Gradio with hash: 8ac54ca7902a04ede2cb93a11ff42c6cb011b296...
Traceback (most recent call last):
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe-v3\launch.py", line 180, in <module>
    git_clone(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe-v3\launch.py", line 151, in git_clone
    run(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe-v3\launch.py", line 45, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 8ac54ca7902a04ede2cb93a11ff42c6cb011b296 for Custom Gradio.
Command: git -C repositories\gradio checkout 8ac54ca7902a04ede2cb93a11ff42c6cb011b296
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: 8ac54ca7902a04ede2cb93a11ff42c6cb011b296


Press any key to continue . . .

**Comment by tomchang25** [comment]
Hello, @twpotato606 @DavidDah 
This should be fixed in v0.3.2b2.

**Comment by twpotato606** [comment]
The newest version did fix this problem, and I can launch the webui now, thank you.
