### ISSUE TITLE
Different results CUDA - CPU

### ISSUE THREAD

**Issue by Milincho** [tomchang25/whisper-auto-transcribe#8]
Results are very different using CUDA or CPU...

This is just an example: 
[tyod-216-2 Subtitles - CPU & CUDA.zip](https://github.com/tomchang25/whisper-auto-transcribe/files/11123625/tyod-216-2.Subtitles.-.CPU.CUDA.zip)

Of course CUDA is like 10x faster or more. But it seems sometimes it just misses a lot. Sometimes there are parts on the video with people clearly talking and there isn't a single subtitle line for a long time...    is this due to the duration of the files?

**Comment by tomchang25** [comment]
#3

**Comment by Milincho** [comment]
> Referring to issue #3

Mmmm...   do you mean it will be fixed also in version 0.3?

**Comment by tomchang25** [comment]
@Milincho It should be fixed by v3.0 If vad and ve are open
